name: jsonexample
description: A demonstration of JSON parsing

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.1
  built_collection: ^4.3.2
  built_value: ^7.0.4

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  built_value_generator: ^7.0.4
  json_serializable: ^3.2.5
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
